### ISSUE TITLE
pull aishifu/ai-shifu-api:latest error

### ISSUE THREAD

**Issue by 450586509** [ai-shifu/ai-shifu#161]
**Describe the bug**
When I used the following command to download the image:

docker pull aishifu/ai-shifu-api:latest
The final output showed the following error:

09dc291590e6: Download complete 
1e399d6a5752: Download complete 
61b7fb31d2d6: Download complete 
00624d325776: Download complete 
failed to register layer: max depth exceeded

**Desktop (please complete the following information):**
 - OS: [macos]

**Comment by yfge** [comment]
Hi, thank you for your issue. We will soon provide an Alibaba Cloud image for users in mainland China.

**Comment by yfge** [comment]
#168
