### ISSUE TITLE
failed to register layer: max depth exceeded

### ISSUE THREAD

**Issue by 450586509** [ai-shifu/ai-shifu#170]
When executing this command:
docker pull image

I receive the following error:
failed to register layer: max depth exceeded

Detailed information:

docker pull registry.cn-beijing.aliyuncs.com/ai-shifu/ai-shifu-api:latest
latest: Pulling from ai-shifu/ai-shifu-api
c1e0ef7b956a: Pulling fs layer 
95b894d63c77: Pulling fs layer 
cb5594266b1b: Pulling fs layer 
59d4884f8528: Pulling fs layer 
59d4884f8528: Waiting 
f1351c0b06b1: Waiting 
65af5eafa295: Waiting 
4f4fb700ef54: Pulling fs layer 
83d36f3b6597: Pulling fs layer 
f37c37ba0e1b: Pulling fs layer 
67be903e4d15: Waiting 
3ce689af6307: Pulling fs layer 
27ea83216ed9: Pulling fs layer 
4f4fb700ef54: Waiting 
27ea83216ed9: Waiting 
83d36f3b6597: Waiting 
f37c37ba0e1b: Waiting 
b456c9fb52b5: Pulling fs layer 
b456c9fb52b5: Waiting 
b9aa1df049f1: Pulling fs layer 
f18dfb5d3f66: Waiting 
972ea4a68fe0: Pulling fs layer 
6d56cb80f896: Pulling fs layer 
436bd8b0e67a: Pulling fs layer 
972ea4a68fe0: Waiting 
3fe9cc612a61: Pulling fs layer 
436bd8b0e67a: Waiting 
7c12ed4b9543: Waiting 
a540f287bdb0: Pulling fs layer 
cfff478df573: Pulling fs layer 
a540f287bdb0: Waiting 
3d34fcbc0bea: Pulling fs layer 
53c777a4256d: Pulling fs layer 
6ed7efbfee5c: Pulling fs layer 
fc44d6ec4a56: Pulling fs layer 
096f58563398: Pulling fs layer 
6d56cb80f896: Waiting 
86d7291ff3ef: Pulling fs layer 
537a4d3d3261: Pulling fs layer 
67331d8c661b: Pulling fs layer 
35fc288aa302: Pulling fs layer 
89c35bc91c98: Waiting 
10045b8c6781: Waiting 
448dfd0c3a17: Pulling fs layer 
5ebd18ac5df0: Pulling fs layer 
3d34fcbc0bea: Waiting 
6ed7efbfee5c: Waiting 
2ba5d09e7435: Pulling fs layer 
b4f7134acd73: Waiting 
537a4d3d3261: Waiting 
4e93ae44eab4: Pulling fs layer 
86d7291ff3ef: Waiting 
35fc288aa302: Waiting 
557e5cd5b03f: Waiting 
67331d8c661b: Waiting 
c355bed3931d: Pulling fs layer 
a75815323101: Pulling fs layer 
5ee2009bb09f: Pulling fs layer 
97d8c75d3e5d: Pulling fs layer 
72e2da29bf4a: Pulling fs layer 
1ff0d711630d: Pulling fs layer 
055d4679a662: Pulling fs layer 
5ebd18ac5df0: Waiting 
afad90751c78: Waiting 
27173c8af0a4: Pulling fs layer 
547bd9256ec1: Pulling fs layer 
729d0b485841: Pulling fs layer 
002ad9192d43: Pulling fs layer 
b0ee1a059a84: Pulling fs layer 
c355bed3931d: Waiting 
f26cd927c140: Waiting 
6af74090e0f6: Waiting 
4e93ae44eab4: Waiting 
97d8c75d3e5d: Waiting 
547bd9256ec1: Waiting 
729d0b485841: Waiting 
72e2da29bf4a: Waiting 
002ad9192d43: Waiting 
b0ee1a059a84: Waiting 
f2976ac5980e: Waiting 
70bb479fd04c: Pulling fs layer 
ad29e2592bea: Waiting 
324b987a7bab: Waiting 
9a4a710b8076: Pulling fs layer 
854d04f7d6a2: Waiting 
05c2b17a7c01: Waiting 
3b3faf226447: Pulling fs layer 
6b70411e8623: Pulling fs layer 
db49268e0c61: Pulling fs layer 
f4cf4eec1696: Waiting 
2087ffd26a60: Pulling fs layer 
9e6aef45654a: Pulling fs layer 
1ec6148d56dd: Pulling fs layer 
051e43923320: Pulling fs layer 
bf81b53d495e: Pulling fs layer 
2d6d8f936f8e: Pulling fs layer 
24c993882722: Pulling fs layer 
eab474b29479: Pulling fs layer 
238a8022a285: Pulling fs layer 
8d32b5ca97f3: Pulling fs layer 
937564ad9256: Pulling fs layer 
8ce8373ef18b: Pulling fs layer 
c3deb0eee7c2: Waiting 
93cfee46f951: Pulling fs layer 
c7d9ad8fee3c: Waiting 
3b3faf226447: Waiting 
9d4e5d4cfcf2: Pulling fs layer 
6b70411e8623: Waiting 
1004deb325a3: Pulling fs layer 
69af42178400: Waiting 
db49268e0c61: Waiting 
3886e600c518: Pulling fs layer 
c99928eb2f85: Waiting 
2087ffd26a60: Waiting 
35b58cd988f1: Pulling fs layer 
09dc291590e6: Pulling fs layer 
eab474b29479: Waiting 
f4cf4eec1696: Extracting [==================================================>]  70.13kB/70.13kB
3886e600c518: Download complete 
71d0c0d3d401: Download complete 
cbf195ac07cf: Download complete 
35b58cd988f1: Download complete 
09dc291590e6: Download complete 
1e399d6a5752: Download complete 
61b7fb31d2d6: Download complete 
00624d325776: Download complete 
46b22e2dcea1: Download complete 
c2afb16a28bf: Download complete 
090ac72b81a2: Download complete 
73353e0e04b1: Download complete 
4f0faf1abbc0: Download complete 
750ae9e06c9c: Download complete 
be84aefba45f: Download complete 
705f43f7dbbf: Download complete 
123aa20305e9: Download complete 
e16eebc6eda5: Download complete 
eff6774500f1: Download complete 
4bb2c9cc17a3: Download complete 
**failed to register layer: max depth exceeded**

**Comment by yfge** [comment]
Hi，We've fixed this issue in lastest code.
