### ISSUE TITLE
ai-shifu-api，无法运行

### ISSUE THREAD

**Issue by 2754026865** [ai-shifu/ai-shifu#184]
![image](https://github.com/user-attachments/assets/e9232000-4881-4a2c-abc1-cf93374596b3)
![image](https://github.com/user-attachments/assets/5a7c7c60-d706-4b83-bf9f-f673d95e1be3)
为什么w我已经填写了，但还是报错？？？

**Comment by yfge** [comment]
填写后是否重启docker了？

**Comment by yfge** [comment]
这个在最新的代码中应该已经fix 了。。
