### ISSUE TITLE
部署本地端AI-师傅的时候走到登录时获取不到验证码

### ISSUE THREAD

**Issue by Yifei-Fang** [ai-shifu/ai-shifu#195]
![image](https://github.com/user-attachments/assets/3022962a-6447-4cd6-af2f-edffae89c7c5)

**Comment by yfge** [comment]
你好，设置中有一个万能验证码，配置好了以后可以直接输入万能验证码

**Comment by yfge** [comment]
# Universal verification code
UNIVERSAL_VERIFICATION_CODE="1024"

**Comment by Yifei-Fang** [comment]
我找到那个万用码了，接入短信api要有企业认证什么的

**Comment by yfge** [comment]
嗯，可以直接使用万能验证码进行登录
