### ISSUE TITLE
8081端口中修改课程内容8081端口中并不能更改课程

### ISSUE THREAD

**Issue by 2754026865** [ai-shifu/ai-shifu#199]
例如在8081端口页面中配置课程，然后更新，但是前端的8080端口并不能显示。
![image](https://github.com/user-attachments/assets/91cc705a-be76-43b6-bf1b-49cfe096da3b)

![image](https://github.com/user-attachments/assets/47189ba5-18f7-4662-bec8-ad3c92126eee)

**Comment by yfge** [comment]
这部分我们正在优化

**Comment by aobos** [comment]
这个初始账号和密码是啥？

**Comment by wangkaigeek** [comment]
这个初始账号和密码是啥？

**Comment by yfge** [comment]
> 这个初始账号和密码是啥？
> 
> 

你好 

系统的默认用户: ai-shifu，默认密码: AIshifu@2024

具体配置可以参考docs.ai-shifu.com

**Comment by wangkaigeek** [comment]
> 这部分我们正在优化

这块现在好了不？后台更新后，前台的课程没有变化

**Comment by wangkaigeek** [comment]
<img width="833" alt="截屏2024-11-30 21 55 48" src="https://github.com/user-attachments/assets/f70f71f6-95bb-4b14-ab45-6622f9125129">
这块代码导致了例如在8081端口页面中配置课程，然后更新，但是前端的8080端口并不能显示问题。因为前端没有传过来课程ID，导致走了 AICourse.query.order_by(AICourse.id.asc()).first()这个逻辑，但是有初始化脚本已经把默认的课程初始化进去了，导致每次都是取的默认课程，而不是新加入的课程，可以把这块改成order_by(AICourse.id.desc()). 或者删数据库里的数据暂时解决这个问题

**Comment by yfge** [comment]
是的，我们现在准备更改成在Cook可以看到CourseID，然后直接进行跳转

**Comment by wangkaigeek** [comment]
> 是的，我们现在准备更改成在Cook可以看到CourseID，然后直接进行跳转

嗯嗯，这样后续可以再支持多课程配置了，没有传CourseID的可以跳转到多课程选择页面。不过我感觉目前单课程的情况，如果后续还保留这个CourseID为空的这块逻辑的话，默认选择最新的一条才应该是合理的，因为用户肯定希望的要新的，而不是初始化的模版

**Comment by yfge** [comment]
> > 是的，我们现在准备更改成在Cook可以看到CourseID，然后直接进行跳转
> 
> 嗯嗯，这样后续可以再支持多课程配置了，没有传CourseID的可以跳转到多课程选择页面。不过我感觉目前单课程的情况，如果后续还保留这个CourseID为空的这块逻辑的话，默认选择最新的一条才应该是合理的，因为用户肯定希望的要新的，而不是初始化的模版

现在在配置文件是有一个默认的课程ID的，如果没有配置就会取第一个，而不是最新的一个
我们觉得现在这样的设计比较适合线上直接进行部署，否则加了新课程以后现有的配置都需要进行改动

**Comment by yfge** [comment]
@Kenrick-Zhou  这部分下周高优进行吧

**Comment by yfge** [comment]
> 像这种仓库里源码进行的更新，我该如何更新到自己服务器中拉取的代码？更新的时候不会修改我.env里的东西。

仓库中只是.env.example 不会影响.env

**Comment by yfge** [comment]
拉一下最新的代码试一下，已经做了更新。

**Comment by yfge** [comment]
> 怎么拉取最新的呀，然后不会影响.env

你的.env 是你本地配置的啊，官方文档里只有.env.example

**Comment by feifei8** [comment]
章节管理页面显示No course URL available, it will be generated automatically after updating the chapter information.是哪里配置不对？<img width="741" alt="image" src="https://github.com/user-attachments/assets/41f09a5c-aa22-46de-9080-7f131e5331a6" />
